// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	DeleteSchedule(ctx context.Context, id int64) error
	GetSchedule(ctx context.Context, id int64) (Schedule, error)
	ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]Schedule, error)
}

var _ Querier = (*Queries)(nil)
