version: '3.8'

services:
  auth:
    build:
      context: ./auth
    ports:
      - "4000:4000"  # Example port mapping for the client
    depends_on:
      - auth_db
  auth_db:
    image: postgres
    env_file:
       - ./auth/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    command: ["bash", "-c", "mkdir -p /docker-entrypoint-initdb.d && chmod 644 ./migrations/*.sql"]
  #   build: 
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./auth/.env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata2:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: auth-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  pgdata2:
  redis_data:
