version: '3.8'

services:
  auth:
    build:
      context: ./auth
    ports:
      - "4000:4000"  
    depends_on:
      - auth_db
      - auth_redis
    networks:
      - auth_network
  auth_db:
    image: postgres
    env_file:
       - ./auth/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./auth/migrations:/docker-entrypoint-initdb.d
    networks:
      - auth_network
  auth_redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - auth_network
volumes:
  pgdata2:
  redis_data:
networks:
  auth_network:
    driver: bridge
