// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.0
// source: rpc_create_send_question_config.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSendQuestionConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionConfigId int64  `protobuf:"varint,1,opt,name=question_config_id,json=questionConfigId,proto3" json:"question_config_id,omitempty"`
	Recipient        string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sender           string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *CreateSendQuestionConfigRequest) Reset() {
	*x = CreateSendQuestionConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_send_question_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSendQuestionConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSendQuestionConfigRequest) ProtoMessage() {}

func (x *CreateSendQuestionConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_send_question_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSendQuestionConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateSendQuestionConfigRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_send_question_config_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSendQuestionConfigRequest) GetQuestionConfigId() int64 {
	if x != nil {
		return x.QuestionConfigId
	}
	return 0
}

func (x *CreateSendQuestionConfigRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateSendQuestionConfigRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type CreateSendQuestionConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendQuestionConfig *SendQuestionConfig `protobuf:"bytes,1,opt,name=send_question_config,json=sendQuestionConfig,proto3" json:"send_question_config,omitempty"`
}

func (x *CreateSendQuestionConfigResponse) Reset() {
	*x = CreateSendQuestionConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_send_question_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSendQuestionConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSendQuestionConfigResponse) ProtoMessage() {}

func (x *CreateSendQuestionConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_send_question_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSendQuestionConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateSendQuestionConfigResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_send_question_config_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSendQuestionConfigResponse) GetSendQuestionConfig() *SendQuestionConfig {
	if x != nil {
		return x.SendQuestionConfig
	}
	return nil
}

type SendQuestionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionConfigId int64                  `protobuf:"varint,2,opt,name=question_config_id,json=questionConfigId,proto3" json:"question_config_id,omitempty"`
	Recipient        string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sender           string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Submitted        bool                   `protobuf:"varint,5,opt,name=submitted,proto3" json:"submitted,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SendQuestionConfig) Reset() {
	*x = SendQuestionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_send_question_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendQuestionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendQuestionConfig) ProtoMessage() {}

func (x *SendQuestionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_send_question_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendQuestionConfig.ProtoReflect.Descriptor instead.
func (*SendQuestionConfig) Descriptor() ([]byte, []int) {
	return file_rpc_create_send_question_config_proto_rawDescGZIP(), []int{2}
}

func (x *SendQuestionConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendQuestionConfig) GetQuestionConfigId() int64 {
	if x != nil {
		return x.QuestionConfigId
	}
	return 0
}

func (x *SendQuestionConfig) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendQuestionConfig) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendQuestionConfig) GetSubmitted() bool {
	if x != nil {
		return x.Submitted
	}
	return false
}

func (x *SendQuestionConfig) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_rpc_create_send_question_config_proto protoreflect.FileDescriptor

var file_rpc_create_send_question_config_proto_rawDesc = []byte{
	0x0a, 0x25, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a,
	0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x12, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x22, 0x6c, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x14, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x12,
	0x73, 0x65, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0xe1, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x66, 0x61, 0x67, 0x62, 0x6f, 0x6c, 0x61, 0x2f, 0x45, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x2d, 0x52, 0x50, 0x4d, 0x2d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_send_question_config_proto_rawDescOnce sync.Once
	file_rpc_create_send_question_config_proto_rawDescData = file_rpc_create_send_question_config_proto_rawDesc
)

func file_rpc_create_send_question_config_proto_rawDescGZIP() []byte {
	file_rpc_create_send_question_config_proto_rawDescOnce.Do(func() {
		file_rpc_create_send_question_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_send_question_config_proto_rawDescData)
	})
	return file_rpc_create_send_question_config_proto_rawDescData
}

var file_rpc_create_send_question_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_create_send_question_config_proto_goTypes = []interface{}{
	(*CreateSendQuestionConfigRequest)(nil),  // 0: pb.CreateSendQuestionConfigRequest
	(*CreateSendQuestionConfigResponse)(nil), // 1: pb.CreateSendQuestionConfigResponse
	(*SendQuestionConfig)(nil),               // 2: pb.SendQuestionConfig
	(*timestamppb.Timestamp)(nil),            // 3: google.protobuf.Timestamp
}
var file_rpc_create_send_question_config_proto_depIdxs = []int32{
	2, // 0: pb.CreateSendQuestionConfigResponse.send_question_config:type_name -> pb.SendQuestionConfig
	3, // 1: pb.SendQuestionConfig.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_create_send_question_config_proto_init() }
func file_rpc_create_send_question_config_proto_init() {
	if File_rpc_create_send_question_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_send_question_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSendQuestionConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_send_question_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSendQuestionConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_send_question_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendQuestionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_send_question_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_send_question_config_proto_goTypes,
		DependencyIndexes: file_rpc_create_send_question_config_proto_depIdxs,
		MessageInfos:      file_rpc_create_send_question_config_proto_msgTypes,
	}.Build()
	File_rpc_create_send_question_config_proto = out.File
	file_rpc_create_send_question_config_proto_rawDesc = nil
	file_rpc_create_send_question_config_proto_goTypes = nil
	file_rpc_create_send_question_config_proto_depIdxs = nil
}
