// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: patient.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
  username,
  medical_history,
  provider,
  out_of_network_expenses,
  out_of_pocket_expenses,
  image,
  co_pay
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, username, medical_history, provider, out_of_network_expenses, out_of_pocket_expenses, co_pay, image, created_at
`

type CreatePatientParams struct {
	Username             string   `json:"username"`
	MedicalHistory       []string `json:"medical_history"`
	Provider             string   `json:"provider"`
	OutOfNetworkExpenses string   `json:"out_of_network_expenses"`
	OutOfPocketExpenses  string   `json:"out_of_pocket_expenses"`
	Image                string   `json:"image"`
	CoPay                string   `json:"co_pay"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.Username,
		arg.MedicalHistory,
		arg.Provider,
		arg.OutOfNetworkExpenses,
		arg.OutOfPocketExpenses,
		arg.Image,
		arg.CoPay,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.MedicalHistory,
		&i.Provider,
		&i.OutOfNetworkExpenses,
		&i.OutOfPocketExpenses,
		&i.CoPay,
		&i.Image,
		&i.CreatedAt,
	)
	return i, err
}

const getPatient = `-- name: GetPatient :one
SELECT id, username, medical_history, provider, out_of_network_expenses, out_of_pocket_expenses, co_pay, image, created_at FROM patients
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetPatient(ctx context.Context, username string) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatient, username)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.MedicalHistory,
		&i.Provider,
		&i.OutOfNetworkExpenses,
		&i.OutOfPocketExpenses,
		&i.CoPay,
		&i.Image,
		&i.CreatedAt,
	)
	return i, err
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET
  medical_history = COALESCE($1, medical_history),
  provider = COALESCE($2, provider),
  out_of_network_expenses = COALESCE($3, out_of_network_expenses),
  out_of_pocket_expenses = COALESCE($4, out_of_pocket_expenses),
  image = COALESCE($5, image),
  co_pay = COALESCE($6, co_pay)
WHERE
  username = $7
RETURNING id, username, medical_history, provider, out_of_network_expenses, out_of_pocket_expenses, co_pay, image, created_at
`

type UpdatePatientParams struct {
	MedicalHistory       []string    `json:"medical_history"`
	Provider             pgtype.Text `json:"provider"`
	OutOfNetworkExpenses pgtype.Text `json:"out_of_network_expenses"`
	OutOfPocketExpenses  pgtype.Text `json:"out_of_pocket_expenses"`
	Image                pgtype.Text `json:"image"`
	CoPay                pgtype.Text `json:"co_pay"`
	Username             string      `json:"username"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.MedicalHistory,
		arg.Provider,
		arg.OutOfNetworkExpenses,
		arg.OutOfPocketExpenses,
		arg.Image,
		arg.CoPay,
		arg.Username,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.MedicalHistory,
		&i.Provider,
		&i.OutOfNetworkExpenses,
		&i.OutOfPocketExpenses,
		&i.CoPay,
		&i.Image,
		&i.CreatedAt,
	)
	return i, err
}
