// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClinician(ctx context.Context, arg CreateClinicianParams) (Clinician, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreatePatientClinicianMapping(ctx context.Context, arg CreatePatientClinicianMappingParams) (PatientClinicianMapping, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	CreateVerifyForgotPassword(ctx context.Context, arg CreateVerifyForgotPasswordParams) (VerifyForgotPassword, error)
	CreateVerifyInvitation(ctx context.Context, arg CreateVerifyInvitationParams) (VerifyInvitation, error)
	GetClinician(ctx context.Context, username string) (Clinician, error)
	GetPatient(ctx context.Context, username string) (Patient, error)
	GetPatientClinicianMapping(ctx context.Context, sender string) (PatientClinicianMapping, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetVerifyEmail(ctx context.Context, username string) (VerifyEmail, error)
	GetVerifyForgotPassword(ctx context.Context, username string) (VerifyForgotPassword, error)
	GetVerifyInvitation(ctx context.Context, id int64) (VerifyInvitation, error)
	ListAcceptedPatientClinicianMapping(ctx context.Context, arg ListAcceptedPatientClinicianMappingParams) ([]PatientClinicianMapping, error)
	// Adjust the number as needed
	ListPatientClinicianMapping(ctx context.Context, arg ListPatientClinicianMappingParams) ([]PatientClinicianMapping, error)
	UpdateClinician(ctx context.Context, arg UpdateClinicianParams) (Clinician, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	//   sender = sqlc.arg(sender) -- OR recipient email
	UpdatePatientClinicianMapping(ctx context.Context, arg UpdatePatientClinicianMappingParams) (PatientClinicianMapping, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
	UpdateVerifyForgotPassword(ctx context.Context, arg UpdateVerifyForgotPasswordParams) (VerifyForgotPassword, error)
	UpdateVerifyInvitation(ctx context.Context, arg UpdateVerifyInvitationParams) (VerifyInvitation, error)
}

var _ Querier = (*Queries)(nil)
