// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: rpc_create_clinician.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClinicianRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials   []string `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Specialties   []string `protobuf:"bytes,2,rep,name=specialties,proto3" json:"specialties,omitempty"`
	ClinicName    string   `protobuf:"bytes,3,opt,name=clinic_name,json=clinicName,proto3" json:"clinic_name,omitempty"`
	ClinicId      string   `protobuf:"bytes,4,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	Image         string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	AcceptPatient bool     `protobuf:"varint,6,opt,name=accept_patient,json=acceptPatient,proto3" json:"accept_patient,omitempty"`
}

func (x *CreateClinicianRequest) Reset() {
	*x = CreateClinicianRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_clinician_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClinicianRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClinicianRequest) ProtoMessage() {}

func (x *CreateClinicianRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_clinician_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClinicianRequest.ProtoReflect.Descriptor instead.
func (*CreateClinicianRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_clinician_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClinicianRequest) GetCredentials() []string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *CreateClinicianRequest) GetSpecialties() []string {
	if x != nil {
		return x.Specialties
	}
	return nil
}

func (x *CreateClinicianRequest) GetClinicName() string {
	if x != nil {
		return x.ClinicName
	}
	return ""
}

func (x *CreateClinicianRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *CreateClinicianRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateClinicianRequest) GetAcceptPatient() bool {
	if x != nil {
		return x.AcceptPatient
	}
	return false
}

type CreateClinicianResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clinician *Clinician `protobuf:"bytes,1,opt,name=clinician,proto3" json:"clinician,omitempty"`
}

func (x *CreateClinicianResponse) Reset() {
	*x = CreateClinicianResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_clinician_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClinicianResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClinicianResponse) ProtoMessage() {}

func (x *CreateClinicianResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_clinician_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClinicianResponse.ProtoReflect.Descriptor instead.
func (*CreateClinicianResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_clinician_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClinicianResponse) GetClinician() *Clinician {
	if x != nil {
		return x.Clinician
	}
	return nil
}

var File_rpc_create_clinician_proto protoreflect.FileDescriptor

var file_rpc_create_clinician_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x69,
	0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0f, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x6e,
	0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x70,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63,
	0x69, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6c, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63,
	0x69, 0x61, 0x6e, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x66, 0x61, 0x67, 0x62, 0x6f, 0x6c, 0x61, 0x2f, 0x45, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2d, 0x52, 0x50, 0x4d, 0x2d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_clinician_proto_rawDescOnce sync.Once
	file_rpc_create_clinician_proto_rawDescData = file_rpc_create_clinician_proto_rawDesc
)

func file_rpc_create_clinician_proto_rawDescGZIP() []byte {
	file_rpc_create_clinician_proto_rawDescOnce.Do(func() {
		file_rpc_create_clinician_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_clinician_proto_rawDescData)
	})
	return file_rpc_create_clinician_proto_rawDescData
}

var file_rpc_create_clinician_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_clinician_proto_goTypes = []interface{}{
	(*CreateClinicianRequest)(nil),  // 0: pb.CreateClinicianRequest
	(*CreateClinicianResponse)(nil), // 1: pb.CreateClinicianResponse
	(*Clinician)(nil),               // 2: pb.Clinician
}
var file_rpc_create_clinician_proto_depIdxs = []int32{
	2, // 0: pb.CreateClinicianResponse.clinician:type_name -> pb.Clinician
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_clinician_proto_init() }
func file_rpc_create_clinician_proto_init() {
	if File_rpc_create_clinician_proto != nil {
		return
	}
	file_clinician_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_clinician_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClinicianRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_clinician_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClinicianResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_clinician_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_clinician_proto_goTypes,
		DependencyIndexes: file_rpc_create_clinician_proto_depIdxs,
		MessageInfos:      file_rpc_create_clinician_proto_msgTypes,
	}.Build()
	File_rpc_create_clinician_proto = out.File
	file_rpc_create_clinician_proto_rawDesc = nil
	file_rpc_create_clinician_proto_goTypes = nil
	file_rpc_create_clinician_proto_depIdxs = nil
}
