// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: rpc_verify_invitation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyInvitationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretCode        int64  `protobuf:"varint,1,opt,name=secret_code,json=secretCode,proto3" json:"secret_code,omitempty"`
	RecipientUsername string `protobuf:"bytes,2,opt,name=recipient_username,json=recipientUsername,proto3" json:"recipient_username,omitempty"`
	RecipientEmail    string `protobuf:"bytes,3,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	Sender            string `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *VerifyInvitationRequest) Reset() {
	*x = VerifyInvitationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_verify_invitation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInvitationRequest) ProtoMessage() {}

func (x *VerifyInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_verify_invitation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInvitationRequest.ProtoReflect.Descriptor instead.
func (*VerifyInvitationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_verify_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyInvitationRequest) GetSecretCode() int64 {
	if x != nil {
		return x.SecretCode
	}
	return 0
}

func (x *VerifyInvitationRequest) GetRecipientUsername() string {
	if x != nil {
		return x.RecipientUsername
	}
	return ""
}

func (x *VerifyInvitationRequest) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *VerifyInvitationRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type VerifyInvitationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteAccepted bool `protobuf:"varint,1,opt,name=invite_accepted,json=inviteAccepted,proto3" json:"invite_accepted,omitempty"`
}

func (x *VerifyInvitationResponse) Reset() {
	*x = VerifyInvitationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_verify_invitation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInvitationResponse) ProtoMessage() {}

func (x *VerifyInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_verify_invitation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInvitationResponse.ProtoReflect.Descriptor instead.
func (*VerifyInvitationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_verify_invitation_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyInvitationResponse) GetInviteAccepted() bool {
	if x != nil {
		return x.InviteAccepted
	}
	return false
}

var File_rpc_verify_invitation_proto protoreflect.FileDescriptor

var file_rpc_verify_invitation_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0xaa, 0x01, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2d,
	0x0a, 0x12, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x43,
	0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x66, 0x61, 0x67, 0x62, 0x6f, 0x6c, 0x61, 0x2f, 0x45, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2d, 0x52, 0x50, 0x4d, 0x2d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_verify_invitation_proto_rawDescOnce sync.Once
	file_rpc_verify_invitation_proto_rawDescData = file_rpc_verify_invitation_proto_rawDesc
)

func file_rpc_verify_invitation_proto_rawDescGZIP() []byte {
	file_rpc_verify_invitation_proto_rawDescOnce.Do(func() {
		file_rpc_verify_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_verify_invitation_proto_rawDescData)
	})
	return file_rpc_verify_invitation_proto_rawDescData
}

var file_rpc_verify_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_verify_invitation_proto_goTypes = []interface{}{
	(*VerifyInvitationRequest)(nil),  // 0: pb.VerifyInvitationRequest
	(*VerifyInvitationResponse)(nil), // 1: pb.VerifyInvitationResponse
}
var file_rpc_verify_invitation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_verify_invitation_proto_init() }
func file_rpc_verify_invitation_proto_init() {
	if File_rpc_verify_invitation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_verify_invitation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInvitationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_verify_invitation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInvitationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_verify_invitation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_verify_invitation_proto_goTypes,
		DependencyIndexes: file_rpc_verify_invitation_proto_depIdxs,
		MessageInfos:      file_rpc_verify_invitation_proto_msgTypes,
	}.Build()
	File_rpc_verify_invitation_proto = out.File
	file_rpc_verify_invitation_proto_rawDesc = nil
	file_rpc_verify_invitation_proto_goTypes = nil
	file_rpc_verify_invitation_proto_depIdxs = nil
}
