// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuestionConfig(ctx context.Context, arg CreateQuestionConfigParams) (QuestionConfig, error)
	DeleteQuestion(ctx context.Context, id int64) error
	DeleteQuestionConfig(ctx context.Context, id int64) error
	GetQuestion(ctx context.Context, id int64) (Question, error)
	GetQuestionConfig(ctx context.Context, id int64) (QuestionConfig, error)
	ListQuestionConfigs(ctx context.Context, arg ListQuestionConfigsParams) ([]QuestionConfig, error)
	ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateQuestionConfig(ctx context.Context, arg UpdateQuestionConfigParams) (QuestionConfig, error)
}

var _ Querier = (*Queries)(nil)
